name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, you can install them here
        pip install -r requirements.txt

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Run the multi-window application test
      env: 
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        # Start Xvfb in the background
        Xvfb :99 -screen 0 1024x768x16 &
        export DISPLAY=:99
        python test_multi_window_app.py
        python REISED.PY
